### ISSUE TITLE
paramsForServer and paramsFromClient  is not a function

### ISSUE THREAD

**Issue by juancampuzano** [marshallswain/feathers-graph-populate#2]
`const { paramsForServer } = require('feathers-graph-populate');
const { paramsFromClient } = require('feathers-graph-populate');`

When I use either of the two requires, I get the following error:

> Uncaught TypeError: paramsForServer is not a function

**Comment by marshallswain** [comment]
Thanks for reporting, @juancampuzano!  Somehow I failed to include them in the repo.  Please try again with `feathers-graph-populate@1.0.4`.  `paramsForServer` is a CommonJS module.  Please let me know if you have any issues using it.

**Comment by juancampuzano** [comment]
Thanks for your Help! Now I am getting the following error: 
`TypeError: makeShallowPopulate is not a function at deepPopulateHook`

**Comment by marshallswain** [comment]
Weird.  I don’t know how this is working for me in my project.  I’ll get back to you.

**Comment by marshallswain** [comment]
@juancampuzano, please upgrade to the latest patch release, I believe it's `feathers-graph-populate@1.0.5`.  Should be fixed, now

**Comment by juancampuzano** [comment]
@marshallswain  Thank you very much, I will review and I will tell you.

**Comment by marshallswain** [comment]
@juancampuzano I'm going to go ahead and close this.  Please let me know if there's still an issue.
