### ISSUE TITLE
update feathers-shallow-populate

### ISSUE THREAD

**Issue by fratzinger** [marshallswain/feathers-graph-populate#27]
See https://github.com/Mattchewone/feathers-shallow-populate/pull/22 from @areiterer

As of `^1.4.0` I come across the same problem as @areiterer figured out. Populating an empty object instead of not setting the item at all, leads to many items in my `FeathersVuex` which are empty `temp` records.

Version `^1.2.0` which I used lastly did not behave that way. I'm afraid it's a problem I introduced with my changes. Sorry about that!

Please @marshallswain, it would be really nice if you could make this a `feathers-shallow-populate` release and update the dependency in `feathers-graph-populate` to that version.

As always, I highly appreciate your work! Thanks in advance!

**Comment by marshallswain** [comment]
@fratzinger  I'm updating the deps, now.  Stay tuned for a release number.  :)

**Comment by fratzinger** [comment]
whoop whoop. Thank you! :)

**Comment by marshallswain** [comment]
Released as `feathers-graph-populate@1.4.1`.

**Comment by fratzinger** [comment]
Nice! Thanks again!

**Comment by areiterer** [comment]
Thanks a lot!
