### ISSUE TITLE
RFC: move shallow-populate, `service` as function & `transformResult`

### ISSUE THREAD

**Issue by fratzinger** [marshallswain/feathers-graph-populate#28]
### 1. move `feathers-shallow-populate` to `feathers-graph-populate`:
Maintaining both feels like a blocker. It's hard to test if I have changes for both. It's inconvenient for you marshall to make it both a release. It's an open door for unexpected bugs.
Option 1: Leave that as is. Separate repositories.
Option 2: Include `shallowPopulate` hook into the repo. Also move the tests (of course)
Option 3: Make it a monorepo

### 2. Make every option a function (starting with `service`):
My last changes with `requestPerItem` introduced a mechanism to populate based on conditions but there's another step to take.
**Explanation**: I've a service called `changelogs` with entries to almost every service with columns: `associatedServicePath`, `associatedId`, `userId`.
If I want to populate the associated Item, I need to take the `associatedServicePath`. The most elegant way would be to have:
```js
associatedItem: {
    service: (item, context) => item.associatedServicePath,
    nameAs: associatedItem, // or even `nameAs: (item, context) => singularize(item.associatedServicePath)`
    asArray: false
  },
```

### 3. `transformResult`:
I've an app with customers and orders. In my frontend I've a table with customers and a column with `ordersCount`. I would like to populate that with `graph-populate`. So dynamically populate a number to an item.
A possible way would be:
```js
ordersCount: {
    service: 'orders',
    nameAs: 'ordersCount',
    params: { query: { limit: 0 }, paginate: true }
    transformResult: (item, context) => item.total
  },
```

I know that fades away from the awesome approach of batch loading, but (2) and (3) would add even more functionality to `feathers-shallow-populate` and `feathers-graph-populate`.

Marshall, what do you think about these points?

**Comment by marshallswain** [comment]
I like all of them.  I especially like combining them into a single repo.  No monorepo is necessary.

**Comment by fratzinger** [comment]
I'll come up with something then :)
