### ISSUE TITLE
Add full working example to docs

### ISSUE THREAD

**Issue by Teomik129** [marshallswain/feathers-graph-populate#4]
There's currently a disconnect in the docs between [defining the relationships](https://feathers-graph-populate.netlify.app/getting-started.html#define-the-relationships) and [creating named queries](https://feathers-graph-populate.netlify.app/getting-started.html#create-named-queries). It's unclear what all of the options for a `populates` entry do. A full working example repo/doc would be helpful!

**Comment by marshallswain** [comment]
I completely agree. I'm not sure when I'll get to this, but thanks for filing this issue as my reminder.

**Comment by netwrkx** [comment]
@marshallswain any luck with this

**Comment by marshallswain** [comment]
I forgot that there's already a full example in this repo: https://github.com/marshallswain/feathers-graph-populate/tree/master/src

Check the hooks file for each service to see the current setup.  You'll see that the relationships are defined in the service.schema.js file, but I generally just put them at the top of the hooks file, now.
